---
title: "The Representation of Hand Postures and Movements in Somatosensory Cortex"
output: html_document
---
<br>
<h4>Authors</h4>
<b>Goodman, J. M.</b><br>
Lee, A. S.<br>
Suresh, A. S.<br>
Hatsopoulos, N. G.<br>
Bensmaia, S. J.<br>
<br><br>

<h4>Abstract</h4>
Despite the remarkable complexity of the hands, we are able to use them effortlessly to grasp and manipulate objects. To achieve dexterous object manipulation requires not only a sophisticated motor system to move the hand but also a sensory system to provide proprioceptive feedback on the consequences of those movements. To investigate hand proprioception in cortex, we simultaneously record time-varying joint kinematics of the hand – measured using a camera-based motion tracking system – and neural activity from somatosensory cortex of rhesus macaques – using chronically implanted electrode arrays – as they perform a wide range of natural grasping movements and undergo passive hand movements. We also record from primary motor cortex (M1) to compare sensory and motor representations of the hand. We find that, during active grasping movements, somatosensory representations of kinematics are very similar to their motor counterparts, with spiking activity from both preferentially encoding the future changes in posture (rather than the velocities) of multiple joints spanning the entire hand. However, during passive manipulation of the hand, somatosensory neurons encode the postural changes of fewer joints with spiking activity that lags, rather than leads, those kinematics. That sensorimotor representations of the hand encode postural changes of the digits stands in contrast to similar representations of the arm, where velocities are preferentially encoded, and suggests that the different functions of the arm and hand give rise to different types of kinematic representations. Moreover, that somatosensory representations of hand kinematics reflect their motor counterparts during volitional movements, but not during passive movements, suggests that proprioceptive somatosensory cortex integrates both peripheral afferent and central motor inputs.<br>