---
title: "Ongoing Projects"
output: html_document
---

<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="./css/academicons.min.css"/>

### Action Execution and Observation

Neurons in several cortical areas respond during both the execution of movement and the mere observation thereof. I am using parallel recordings across multiple cortical areas involved in the control of hand movements and state-of-the-art analysis techniques to study this phenomenon. I aim to determine whether there indeed exists a specific class of neurons that are especially responsive to observed movements and whether the cortical representation of movement during action observation bears detailed or merely coarse similarities to that seen during action execution. Stay tuned for presentations, a publication, and a GitHub repository!

### Demonstrating a Closed-Loop Brain-Computer Interface (BCI)

I am currently involved in the B-CRATOS project, which aims to demonstrate a closed-loop BCI in non-human primates. This BCI will allow for bidirectional communication with a robotic hand to enable both motor control and somatosensory feedback. It will also address numerous engineering challenges that, to date, have confined intracortical BCIs to a laboratory setting. See the project website ([link](https://www.b-cratos.eu/)) for details.
