---
title: "Publications"
output: html_document
---

<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="./css/academicons.min.css"/>


<br>
<h4>First Author Publications</h4>
<i>(* indicates equal contribution)</i>

<b>Goodman, J.M.</b>, Tabot, G.A., Lee, A.S., Suresh, A.K., Rajan, A.T., Hatsopoulos, N.G., & Bensmaia, S.J. (2019). Postural Representations of the Hand in Primate Sensorimotor Cortex. Neuron 104(5), 1000–1009.e7. ([PubMed link](https://pubmed.ncbi.nlm.nih.gov/31668844))<br><br>

<b>Goodman, J.M.</b>, & Bensmaia, S.J. (2018). The neural basis of haptic perception. In: The Stevens Handbook of Experimental Psychology and Cognitive Neuroscience. Fourth Edition. Volume 2: Sensation, Perception, & Attention. Eds. Wixted, J.T. and Serences, J.T. John Wiley & Sons, New York, NY. ([Publisher link](https://onlinelibrary.wiley.com/doi/abs/10.1002/9781119170174.epcn205))<br><br>

<b>Goodman, J.M.</b>, & Bensmaia, S.J. (2017). A variation code accounts for the perceived roughness of coarsely textured surfaces. Scientific Reports 7. ([PubMed link](https://pubmed.ncbi.nlm.nih.gov/28440308/))<br><br>

Dougherty, J.B.\*, <b>Goodman, J.M.\*</b>, Knudsen, E.B., & Moxon, K.A. (2012). Controlled unilateral isometric force generated by epidural spinal cord stimulation in the rat hindlimb. IEEE Transatctions on Neural Systems and Rehabilitation Engineering (TNSRE) 20(4), 549–556. ([PubMed link](https://pubmed.ncbi.nlm.nih.gov/22717526/))<br><br><br>

<h4>Other Publications</h4>

Yan, Y., <b>Goodman, J.M.</b>, Moore, D.D., Solla, S.A., & Bensmaia, S.J. (2020). Unexpected complexity of everyday manual behaviors. Nature Communications 11(1). ([PubMed link](https://pubmed.ncbi.nlm.nih.gov/32678102/))<br><br>

Okorokova, E.V., <b>Goodman, J.M.</b>, Hatsopoulos, N.G., & Bensmaia, S.J. (2020). Decoding hand kinematics from population responses in sensorimotor cortex during grasping. Journal of Neural Engineering in press. ([PubMed link](https://pubmed.ncbi.nlm.nih.gov/32442987/))<br><br>

Prendergast, B., Brooks, J., <b>Goodman, J.M.</b>, Boyarinova, M., Winberry, J.E., & Bensmaia, S.J. (2019). Finger Posture and Finger Load are Perceived Independently. Scientific Reports 9. ([PubMed link](https://pubmed.ncbi.nlm.nih.gov/31636297/))<br><br>

Dougherty, J.B., Knudsen, E.B., <b>Goodman, J.M.</b>, & Moxon, K.A. (2011). Response mapping for epidural spinal stimulation for the restoration of controlled hindlimb movement after spinal cord injury. 2011 5th International IEEE/EMBS Conference on Neural Engineering Cancun, 338–341. Conference Proceedings. ([IEEE Xplore link](https://ieeexplore.ieee.org/document/5910556))<br><br>
<br>


<h4>Preprints</h4>
<i>(* indicates equal contribution)</i>

Suresh, A.K.\*, <b>Goodman, J.M.\*</b>, Okorokova, E.V., Kaufman, M.T., Hatsopoulos, N.G., & Bensmaia, S.J. (2019). Neural population dynamics in motor cortex are different for reach and grasp. bioRxiv 667196. Pre-print. ([bioRxiv link](https://www.biorxiv.org/content/10.1101/667196v3))<br><br>